version: '3'
services:
  reminders_back:
    build: ./reminders_back
    container_name: reminders_back
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
      - ./code/static:/code/static
    environment:
      - DJANGO_SETTINGS_MODULE=reminders_back.container_settings
    ports:
      - 8000:8000
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data/

  celery:
    build: ./reminders_back
    container_name: celery
    command: celery -A reminders_back worker --loglevel=info
    volumes:
      - ./reminders_back:/usr/src/app
    depends_on:
      - reminders_back
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=reminders_back.container_settings

  celery-beat:
    build: ./reminders_back
    container_name: celery-beat
    command: celery -A reminders_back beat -l debug
    volumes:
      - ./reminders_back:/usr/src/app
    depends_on:
      - redis

  flower:
    build: ./reminders_back
    container_name: flower
    command: flower -A reminders_back --port=10112 --broker=redis://redis:6379/0
    ports:
      - 10112:10112
    depends_on:
      - reminders_back
      - redis
      - celery
      - celery-beat

  redis:
    image: "redis:alpine"
    container_name: redis

volumes:
  postgres_data:
