version: '3'
services:
  reminders_back:
    build: reminders_back/.
    container_name: reminders_back
    depends_on:
      - redis
    restart: always
    volumes:
      - ./code/static:/code/static
    ports:
      - "8000:8000"
      - "10112:10112"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
