version: '3'
services:
  reminders_back:
    build: ./reminders_back
    container_name: reminders_back
    depends_on:
      - redis
    restart: always
    volumes:
      - ./code/static:/code/static
    ports:
      - "8000:8000"

  celery:
    build: ./reminders_back
    command: celery -A reminders_back worker --loglevel=info
    volumes:
      - ./reminders_back:/usr/src/app
    depends_on:
      - reminders_back
      - redis

  redis:
    image: "redis:alpine"
