version: '3'
services:
  reminders_back:
    build: ./reminders_back
    container_name: reminders_back
    depends_on:
      - redis
    restart: always
    volumes:
      - ./code/static:/code/static
    ports:
      - "8000:8000"

  celery:
    build: ./reminders_back
    container_name: celery
    command: celery -A reminders_back worker --loglevel=info
    volumes:
      - ./reminders_back:/usr/src/app
    depends_on:
      - reminders_back
      - redis

  flower:
    build: ./reminders_back
    container_name: flower
    command: flower -A reminders_back --port=10112 --broker=redis://redis:6379/0
    ports:
      - "10112:10112"
    depends_on:
      - reminders_back
      - redis
      - celery

  redis:
    image: "redis:alpine"
    container_name: redis
