# Generated by Django 3.1.4 on 2020-12-05 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст напоминания')),
                ('date', models.DateField(verbose_name='Дата напоминания')),
                ('time', models.TimeField(default=datetime.time(8, 0), verbose_name='Время напоминания')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
            },
        ),
    ]
